### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Arguments
  commentId: N:BindOpen.Application.Arguments
  id: BindOpen.Application.Arguments
  children:
  - BindOpen.Application.Arguments.AppArgumentHelper
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Arguments
  nameWithType: BindOpen.Application.Arguments
  fullName: BindOpen.Application.Arguments
  type: Namespace
  assemblies:
  - BindOpen.Runtime
references:
- uid: BindOpen.Application.Arguments.AppArgumentHelper
  commentId: T:BindOpen.Application.Arguments.AppArgumentHelper
  isExternal: true
  name: AppArgumentHelper
  nameWithType: AppArgumentHelper
  fullName: BindOpen.Application.Arguments.AppArgumentHelper
shouldSkipMarkup: true
