### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Products
  commentId: N:BindOpen.Application.Products
  id: BindOpen.Application.Products
  children:
  - BindOpen.Application.Products.ProductInformation
  - BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
  - BindOpen.Application.Products.ProductInformation.ProductKind
  - BindOpen.Application.Products.ProductInformation.SupportedLanguage
  - BindOpen.Application.Products.ProductRegistrationMode
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Products
  nameWithType: BindOpen.Application.Products
  fullName: BindOpen.Application.Products
  type: Namespace
  assemblies:
  - BindOpen.Runtime
references:
- uid: BindOpen.Application.Products.ProductInformation
  commentId: T:BindOpen.Application.Products.ProductInformation
  name: ProductInformation
  nameWithType: ProductInformation
  fullName: BindOpen.Application.Products.ProductInformation
- uid: BindOpen.Application.Products.ProductInformation.SupportedLanguage
  commentId: T:BindOpen.Application.Products.ProductInformation.SupportedLanguage
  parent: BindOpen.Application.Products
  name: ProductInformation.SupportedLanguage
  nameWithType: ProductInformation.SupportedLanguage
  fullName: BindOpen.Application.Products.ProductInformation.SupportedLanguage
- uid: BindOpen.Application.Products.ProductInformation.ProductKind
  commentId: T:BindOpen.Application.Products.ProductInformation.ProductKind
  parent: BindOpen.Application.Products
  name: ProductInformation.ProductKind
  nameWithType: ProductInformation.ProductKind
  fullName: BindOpen.Application.Products.ProductInformation.ProductKind
- uid: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
  commentId: T:BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
  parent: BindOpen.Application.Products
  name: ProductInformation.ProductAffiliateNetwork
  nameWithType: ProductInformation.ProductAffiliateNetwork
  fullName: BindOpen.Application.Products.ProductInformation.ProductAffiliateNetwork
- uid: BindOpen.Application.Products.ProductRegistrationMode
  commentId: T:BindOpen.Application.Products.ProductRegistrationMode
  parent: BindOpen.Application.Products
  name: ProductRegistrationMode
  nameWithType: ProductRegistrationMode
  fullName: BindOpen.Application.Products.ProductRegistrationMode
- uid: BindOpen.Application.Products
  commentId: N:BindOpen.Application.Products
  name: BindOpen.Application.Products
  nameWithType: BindOpen.Application.Products
  fullName: BindOpen.Application.Products
shouldSkipMarkup: true
