### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Options
  commentId: N:BindOpen.Application.Options
  id: BindOpen.Application.Options
  children:
  - BindOpen.Application.Options.IOptionSet
  - BindOpen.Application.Options.IOptionSpec
  - BindOpen.Application.Options.IOptionSpecSet
  - BindOpen.Application.Options.OptionNameKind
  - BindOpen.Application.Options.OptionNameKindExtension
  - BindOpen.Application.Options.OptionSet
  - BindOpen.Application.Options.OptionSpec
  - BindOpen.Application.Options.OptionSpecSet
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Options
  nameWithType: BindOpen.Application.Options
  fullName: BindOpen.Application.Options
  type: Namespace
  assemblies:
  - BindOpen.Runtime
references:
- uid: BindOpen.Application.Options.IOptionSet
  commentId: T:BindOpen.Application.Options.IOptionSet
  parent: BindOpen.Application.Options
  name: IOptionSet
  nameWithType: IOptionSet
  fullName: BindOpen.Application.Options.IOptionSet
- uid: BindOpen.Application.Options.IOptionSpec
  commentId: T:BindOpen.Application.Options.IOptionSpec
  parent: BindOpen.Application.Options
  name: IOptionSpec
  nameWithType: IOptionSpec
  fullName: BindOpen.Application.Options.IOptionSpec
- uid: BindOpen.Application.Options.IOptionSpecSet
  commentId: T:BindOpen.Application.Options.IOptionSpecSet
  parent: BindOpen.Application.Options
  name: IOptionSpecSet
  nameWithType: IOptionSpecSet
  fullName: BindOpen.Application.Options.IOptionSpecSet
- uid: BindOpen.Application.Options.OptionNameKind
  commentId: T:BindOpen.Application.Options.OptionNameKind
  parent: BindOpen.Application.Options
  name: OptionNameKind
  nameWithType: OptionNameKind
  fullName: BindOpen.Application.Options.OptionNameKind
- uid: BindOpen.Application.Options.OptionNameKindExtension
  commentId: T:BindOpen.Application.Options.OptionNameKindExtension
  parent: BindOpen.Application.Options
  name: OptionNameKindExtension
  nameWithType: OptionNameKindExtension
  fullName: BindOpen.Application.Options.OptionNameKindExtension
- uid: BindOpen.Application.Options.OptionSet
  commentId: T:BindOpen.Application.Options.OptionSet
  name: OptionSet
  nameWithType: OptionSet
  fullName: BindOpen.Application.Options.OptionSet
- uid: BindOpen.Application.Options.OptionSpec
  commentId: T:BindOpen.Application.Options.OptionSpec
  parent: BindOpen.Application.Options
  name: OptionSpec
  nameWithType: OptionSpec
  fullName: BindOpen.Application.Options.OptionSpec
- uid: BindOpen.Application.Options.OptionSpecSet
  commentId: T:BindOpen.Application.Options.OptionSpecSet
  name: OptionSpecSet
  nameWithType: OptionSpecSet
  fullName: BindOpen.Application.Options.OptionSpecSet
- uid: BindOpen.Application.Options
  commentId: N:BindOpen.Application.Options
  name: BindOpen.Application.Options
  nameWithType: BindOpen.Application.Options
  fullName: BindOpen.Application.Options
shouldSkipMarkup: true
