### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Rights
  commentId: N:BindOpen.Application.Rights
  id: BindOpen.Application.Rights
  children:
  - BindOpen.Application.Rights.ApplicationPrivilege
  - BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  - BindOpen.Application.Rights.UserPermission
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Rights
  nameWithType: BindOpen.Application.Rights
  fullName: BindOpen.Application.Rights
  type: Namespace
  assemblies:
  - BindOpen.Runtime
references:
- uid: BindOpen.Application.Rights.ApplicationPrivilege
  commentId: T:BindOpen.Application.Rights.ApplicationPrivilege
  name: ApplicationPrivilege
  nameWithType: ApplicationPrivilege
  fullName: BindOpen.Application.Rights.ApplicationPrivilege
- uid: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  commentId: T:BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
  parent: BindOpen.Application.Rights
  name: ApplicationPrivilege.ApplicationPrivilegeEntityKind
  nameWithType: ApplicationPrivilege.ApplicationPrivilegeEntityKind
  fullName: BindOpen.Application.Rights.ApplicationPrivilege.ApplicationPrivilegeEntityKind
- uid: BindOpen.Application.Rights.UserPermission
  commentId: T:BindOpen.Application.Rights.UserPermission
  parent: BindOpen.Application.Rights
  name: UserPermission
  nameWithType: UserPermission
  fullName: BindOpen.Application.Rights.UserPermission
- uid: BindOpen.Application.Rights
  commentId: N:BindOpen.Application.Rights
  name: BindOpen.Application.Rights
  nameWithType: BindOpen.Application.Rights
  fullName: BindOpen.Application.Rights
shouldSkipMarkup: true
