### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Messages
  commentId: N:BindOpen.Application.Messages
  id: BindOpen.Application.Messages
  children:
  - BindOpen.Application.Messages.DisplayMessage
  - BindOpen.Application.Messages.DisplayMessage.DisplayMessageOption
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Messages
  nameWithType: BindOpen.Application.Messages
  fullName: BindOpen.Application.Messages
  type: Namespace
  assemblies:
  - BindOpen.Runtime
references:
- uid: BindOpen.Application.Messages.DisplayMessage
  commentId: T:BindOpen.Application.Messages.DisplayMessage
  name: DisplayMessage
  nameWithType: DisplayMessage
  fullName: BindOpen.Application.Messages.DisplayMessage
- uid: BindOpen.Application.Messages.DisplayMessage.DisplayMessageOption
  commentId: T:BindOpen.Application.Messages.DisplayMessage.DisplayMessageOption
  parent: BindOpen.Application.Messages
  name: DisplayMessage.DisplayMessageOption
  nameWithType: DisplayMessage.DisplayMessageOption
  fullName: BindOpen.Application.Messages.DisplayMessage.DisplayMessageOption
- uid: BindOpen.Application.Messages
  commentId: N:BindOpen.Application.Messages
  name: BindOpen.Application.Messages
  nameWithType: BindOpen.Application.Messages
  fullName: BindOpen.Application.Messages
shouldSkipMarkup: true
