### YamlMime:ManagedReference
items:
- uid: BindOpen.Application.Security
  commentId: N:BindOpen.Application.Security
  id: BindOpen.Application.Security
  children:
  - BindOpen.Application.Security.ApplicationCredential
  - BindOpen.Application.Security.IApplicationCredential
  langs:
  - csharp
  - vb
  name: BindOpen.Application.Security
  nameWithType: BindOpen.Application.Security
  fullName: BindOpen.Application.Security
  type: Namespace
  assemblies:
  - BindOpen.Runtime
references:
- uid: BindOpen.Application.Security.ApplicationCredential
  commentId: T:BindOpen.Application.Security.ApplicationCredential
  name: ApplicationCredential
  nameWithType: ApplicationCredential
  fullName: BindOpen.Application.Security.ApplicationCredential
- uid: BindOpen.Application.Security.IApplicationCredential
  commentId: T:BindOpen.Application.Security.IApplicationCredential
  parent: BindOpen.Application.Security
  name: IApplicationCredential
  nameWithType: IApplicationCredential
  fullName: BindOpen.Application.Security.IApplicationCredential
- uid: BindOpen.Application.Security
  commentId: N:BindOpen.Application.Security
  name: BindOpen.Application.Security
  nameWithType: BindOpen.Application.Security
  fullName: BindOpen.Application.Security
shouldSkipMarkup: true
